[core]
mode = "declared"          # declared | installed
src = ["animadao", "tests"]

# PyPI cache / concurrency
pypi_ttl_seconds = 86400
pypi_concurrency = 8

[ignore]
distributions = ["pip", "setuptools", "wheel", "ruff"]
imports = []
