name: publish
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # если используешь окружение с правилами, раскомментируй:
    # environment: release
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pipx install uv

      - name: Sync deps
        run: uv sync --extra dev

      - name: Build sdist+wheel
        run: uv run python -m build --sdist --wheel

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: uv run twine upload dist/*
